---
title: "Nucseq Microglia Data Analysis"
author: "Neha"
date: "10/22/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## loading packages
```{r}
library(Seurat)
library(dplyr)
library(harmony)
library(ggplot2)
```

##loading 10X files and objects
```{r}
sample4 <- Read10X("raw_data/sample4/")
obj4 <- CreateSeuratObject(counts = sample4, project = "sample4")
obj4
sample5 <- Read10X("raw_data/sample5/")
obj5 <- CreateSeuratObject(counts = sample5, project = "sample5")
obj5
both <- merge(obj4, obj5)
```

##after QC
```{r}
both[["percent.mt"]] <- PercentageFeatureSet(both, pattern = "^mt-")
both <- subset(both, subset = nCount_RNA>= 1000 & nFeature_RNA>= 200 & percent.mt < 80)
VlnPlot(both, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

```

## downstream scRNA analysis
```{r}
project <- "Kimi_nucseq"
scrna <- function(seurat_obj){
  seurat_obj <- Seurat::NormalizeData(seurat_obj, verbose = FALSE) %>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 2000)  
    seurat_obj.genes <- rownames(seurat_obj) 
      seurat_obj <- ScaleData(seurat_obj, features = seurat_obj.genes) %>% 
      RunPCA(features = VariableFeatures(object = seurat_obj)) %>%
      FindNeighbors(dims = 1:10) %>% 
      FindClusters(resolution = 0.5) %>% 
      FindClusters(resolution = 0.8) %>% 
      FindClusters(resolution = 1.0) %>% 
      RunUMAP(dims = 1:10)
    saveRDS(seurat_obj, paste0(project, ".RDS"))
    seurat_obj <- seurat_obj
}

both <- scrna(both)
c25=c("dodgerblue2","#E31A1C" , "green4", "#6A3D9A","#FF7F00" ,"black" , "gold1","skyblue2" ,"#FB9A99" , "palegreen2" , "#CAB2D6" , "#FDBF6F",  "gray70" , "khaki2" ,"maroon" , "orchid1" ,"deeppink1" ,"blue1" ,"steelblue4" ,"darkturquoise", "green1" , "yellow4" , "yellow3", "darkorange4" , "brown" ,"darkcyan" , "darkgoldenrod1", "darkolivegreen4","cornsilk" , "aquamarine1" , "darkseagreen1","honeydew3","salmon" , "slateblue3", "thistle2" , "slategray2","springgreen" , "rosybrown1" , "plum2" , "chocolate"  ,    "blanchedalmond","brown1" , "aliceblue" , "cadetblue1","coral1" , "firebrick1" , "darkslategrey", "darkslateblue", "#745745","#a01b68","#ffc372","#fff0f0","#ebd4d4","#eeeeee","#de4463","#e8ffc1","#19d3da","#ee6f57","#ff9642","#646464","#0072ce","#dc9cbf","#ED8E7C","#F1ECC3","#D9DD6B","#7C83FD","#FDD2BF","#E98580","#C6B4CE","#FFDADA","#B5EAEA","#BB8760","#C9E4C5","#FAEBE0","#F7DBF0","#66DE93","#FFC074","#B2B8A3","#F2F4C3","#D1D9D9","#A7D0CD","#114E60","#28B5B5")

scrna_plots <- function(seurat_obj){
  pdf(paste0(project, "UMAPs.pdf"), 12,8)
  DimPlot(seurat_obj, reduction = "umap", label = TRUE, group.by = "RNA_snn_res.0.5", label.size = 5, cols=c25)
  DimPlot(seurat_obj, reduction = "umap", label = TRUE, group.by = "RNA_snn_res.0.8", label.size = 5, cols=c25)
  DimPlot(seurat_obj, reduction = "umap", label = TRUE, group.by = "RNA_snn_res.1", label.size = 5, cols=c25)
  dev.off()
  
  pdf(paste0(project, "QC_Violin_plot.pdf"), 15,8)
  VlnPlot(seurat_obj, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
  dev.off()
}

plots <- scrna_plots(both)

meta <- both@meta.data %>% mutate(condition = case_when(orig.ident == "sample4" ~ "Tim3 KO, 5XFAD",
                                                        orig.ident == "sample5" ~ "control, 5XFAD"))

DimPlot(seurat_obj, reduction = "umap", label = TRUE, group.by = "condition", label.size = 5)
```

## DEGs
```{r}
Idents(both) <- both@meta.data$##chose resolution
both.markers <- FindAllMarkers(both, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

top5 <- both.markers %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC)
pdf("DEGs_res0.8_Heatmap.pdf", 15,10)
DoHeatmap(both, features = top5$gene, angle = 90, size=3.5, lines.width=1)
dev.off()
```

## harmony
```{r}
library(harmony)
all <- merge(obj4, obj5)
all =Seurat::NormalizeData(all,verbose = FALSE) %>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
    ScaleData(verbose = FALSE) %>% 
    RunPCA(pc.genes = all@var.genes, npcs = 20, verbose = FALSE)

all <- all %>% RunHarmony("orig.ident", plot_convergence = TRUE)
all <- all %>% 
    RunUMAP(reduction = "harmony", dims = 1:20) %>% ##reduction = "harmony"
    FindNeighbors(reduction = "harmony", dims = 1:20) %>% ##reduction = "harmony"
    FindClusters(resolution = 0.5) %>%
    FindClusters(resolution = 0.8) %>% 
    identity()

pdf("UMAP_after_harmony.pdf", width = 15, height = 8)
DimPlot(all, reduction = "umap", group.by = "orig.ident")
dev.off()   

pdf("UMAP_seurat_clusters.pdf", 12,8)
DimPlot(all, reduction = "umap", label = TRUE, cols=c25, group.by="res0.8")
dev.off()

##adding metadata
all@meta.data$barcode <- rownames(all@meta.data)
meta <- all@meta.data %>% mutate(condition = case_when(orig.ident == "sample4" ~ "Tim3 KO, 5XFAD",
                                                        orig.ident == "sample5" ~ "control, 5XFAD"))
head(meta)
rownames(meta) <- meta$barcode
head(meta)
x <- AddMetaData(both, meta)

pdf("UMAP_by_condition.pdf", 12,7)
DimPlot(all, reduction = "umap", label = FALSE, group.by = "condition", label.size = 5)
dev.off()


## DEGs using findallmarkers
all.markers <- FindAllMarkers(all, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
top5 <- all.markers %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC)

pdf("DEGs_res0.8_Heatmap.pdf", 15,10)
DoHeatmap(all, features = top5$gene, angle = 90, size=3.5, lines.width=1)
dev.off()
```

## signature scoring for MGnD genes
```{r}
MGnD_sig <- c("Clec7a", "Lgals3", "Gpnmb", "Itgax", "Spp1", "Ccl2", "Fabp5",
              "Bhlhe40", "Trem2", "Apoe", "Csf1", "Msr1", "Tfec", "Tyrobp",
              "Ctsb", "Ctsd", "Ctsl", "B2m", "Fth1", "Lyz2", "Axl", "Cst7",
              "Lpl", "Cd9", "Csf1", "Ccl6", "Lilrb4a", "Timp2", "Cd63", "Ly9", "Hif1a")

Homeostasis_MG_sig <- c("Smad3", "Hexb", "P2ry12", "Mertk", "Entpd1", "Tmem119", "Tgfbr1",
                        "Spi1", "Mafb", "Mef2a", "Sall1", "Egr1", "Jun", "Siglech")

all <-AddModuleScore(object = all, features =list(MGnD_sig, Homeostasis_MG_sig), name = c("MGnD signature", "Homestasis signature"))

VlnPlot(object = all, features =  c("MGnD.signature1", "Homestasis.signature2"), ncol=2, cols=c25)
```

## exploratory plots for annotations
```{r}
FeaturePlot(both, reduction = "umap", features = c( "Havcr2", "Ly86", "Mertk", "Cd86"), order = TRUE, label = TRUE)

##MGnD cgenes
DotPlot(all, features = c("Clec7a", "Lgals3", "Gpnmb", "Itgax", "Spp1", "Ccl2", "Fabp5",
              "Bhlhe40", "Trem2", "Apoe", "Csf1", "Msr1", "Tfec", "Tyrobp",
              "Ctsb", "Ctsd", "Ctsl", "B2m", "Fth1", "Lyz2", "Axl", "Cst7",
              "Lpl", "Cd9",  "Ccl6", "Lilrb4a", "Timp2", "Cd63", "Ly9", "Hif1a"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))

##oligodendroctes
FeaturePlot(all, reduction = "umap", features = c("Itpr2", "Prom1", "Gpr17", "Tcf7l2", "9630013A20Rik", "Idh1", "Cnksr3", "Rnf122", "Plp1"), order = TRUE, label = TRUE)

##general brain cortex cells
FeaturePlot(all, reduction = "umap", features = c("Tbr1", "Hapln2", "Acta2", "Ly6c1", "Gm11549", "Spink8", "Pnoc"), order = TRUE, label = TRUE, label.size=7)


##interneuron cells
FeaturePlot(all, reduction = "umap", features = c("Gad1", "Pvalb", "Sst", "Htr3a", "Vip", "Reln", "Cck", "Npy", "Lhx6", "Calb2", "Pde1a"), order = TRUE, label = TRUE, label.size=7)
FeaturePlot(all, reduction = "umap", features = c("Lphn2", "Kcnip2", "Rgs10", "Nov", "Cpne5", "Slc5a7", "Crh", "Pax6", "Cxcl14", "Gda", "Sema3e"), order = TRUE, label = TRUE, label.size=7)
DotPlot(all, features = c("Clec7a", "Lgals3", "Gpnmb", "Itgax", "Spp1", "Ccl2", "Fabp5",
              "Bhlhe40", "Trem2", "Apoe", "Csf1", "Msr1", "Tfec", "Tyrobp",
              "Ctsb", "Ctsd", "Ctsl", "B2m", "Fth1", "Lyz2", "Axl", "Cst7",
              "Lpl", "Cd9",  "Ccl6", "Lilrb4a", "Timp2", "Cd63", "Ly9", "Hif1a"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))

DotPlot(all, features = c(), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))

##astrocytes
FeaturePlot(all, reduction = "umap", features = c("Aldh1", "Gfap", "Aqp4", "Serpinf1", "Gja1", "Mfge8", "Slco1c1"), order = TRUE, label = TRUE, label.size=7)

##microglia
FeaturePlot(all, reduction = "umap", features = c("Clec7a","Trem2", "Apoe", "Axl","Aif1", "Mrc1", "Lyve1"), order = TRUE, label = TRUE, label.size=7)

##Dot pplot
DotPlot(all, features = c("Slc1a3", "Pdgfra", "Col20a1", "Olig2", "Prrx1", "Fgfr3", "Slc16a1", "Dio1", "Linc00982", "Gfap", "Aqp4", "Mt1f", "Id3", "Opalin", "Plp1", "Mag", "Klk6", "Nostrin", "Ebf1", "Itih5", "Emcn", "Tyrobp", "C3", "Cx2cr1", "Csf1r"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))

##inhibitory neurons
FeaturePlot(all, reduction = "umap", features = c("Adarb2", "Lhx6", "Sst", "Npy", "Hpgd", "B3gat2", "Calb1", "Frzb", "Th", "Lgr5", "Mepe", "Wfdc2", "Sulf1", "Stk32a"), order = TRUE, label = TRUE, label.size=5)
DotPlot(all, features = c("Adarb2", "Lhx6", "Sst", "Npy", "Hpgd", "B3gat2", "Calb1", "Frzb", "Th", "Lgr5", "Mepe", "Wfdc2", "Sulf1",  "Stk32a"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))

##excitatory neuron
FeaturePlot(all, reduction = "umap", features = c("Lamp5", "Rorb", "Themis", "Fezf2", "Ltk", "Glp2r", "Frem3", "C1ql3", "Esr1", "Col22a1", "Filip1l", "Twist2", "Folh1b", "Sema3e", "Dapk2", "Ttc12", "C1r", "Scn4b", "Crabp1", "Fgf10", "Il26", "Abo", "Il15", "Or2t8"), order = TRUE, label = TRUE, label.size=5)
DotPlot(all, features = c("Lamp5", "Rorb", "Themis", "Fezf2", "Ltk", "Glp2r", "Frem3", "C1ql3", "Esr1", "Col22a1", "Filip1l", "Twist2", "Folh1b", "Sema3e", "Dapk2", "Ttc12", "C1r", "Scn4b", "Crabp1", "Fgf10", "Il26", "Abo", "Il15", "Or2t8"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))
```

## macrophages plots for annotation
```{r}
Macro - c("C1qa", "C1qb", "C1qc", "Cd14", "Siglech",  "Cd86",
"Apoc1", "Apoe", "Dab2", "Lgmn", "Ctsd", "Trem2", "Cd9", "Fcgr3", "Ly6c2", "Ccr2", "Pglyrp1", "Lyz2", "Chil3", "Hp", "Ifitm6", "Msrb1", "Ccl12", "Fn1", "Cd14", "S100a6", "S100a4", "S100a11")

FeaturePlot(all, reduction = "umap", features = c("C1qa", "C1qb", "C1qc", "Cd14", "Siglech",  "Cd86",
"Apoc1", "Apoe", "Dab2", "Lgmn", "Ctsd", "Trem2"), order = TRUE, label = TRUE, label.size=5)
FeaturePlot(all, reduction = "umap", features = c("Cd9", "Fcgr3", "Ly6c2", "Ccr2", "Pglyrp1", "Lyz2", "Chil3", "Hp", "Ifitm6", "Msrb1", "Ccl12", "Fn1", "Cd14", "S100a6", "S100a4", "S100a11"), order = TRUE, label = TRUE, label.size=5)

DotPlot(all, features = c("C1qa", "C1qb", "C1qc", "Cd14", "Siglech",  "Cd86",
"Apoc1", "Apoe", "Dab2", "Lgmn", "Ctsd", "Trem2", "Cd9", "Fcgr3", "Ly6c2", "Ccr2", "Pglyrp1", "Lyz2", "Chil3", "Hp", "Ifitm6", "Msrb1", "Ccl12", "Fn1", "S100a6", "S100a4", "S100a11"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))
```

##cluster 14 DEGs
```{r}
FeaturePlot(all, reduction = "umap", features = c("Tgfbr1", "Inpp5d", "Pdxdc2", "Dock8"), order = TRUE, label = TRUE, label.size=5)
```

##subsetting cluster 14
```{r}

cluster14 <- subset(all, subset = seurat_clusters %in% "14")
cluster14 <- FindVariableFeatures(cluster14, selection.method = "vst", nfeatures = 2000) 
cluster14 <-  RunPCA(cluster14, features = VariableFeatures(object = cluster14))
cluster14 <- FindNeighbors(cluster14, dims = 1:20) 
cluster14 <- FindClusters(cluster14, resolution = 0.4)
cluster14 <- FindClusters(cluster14, resolution = 0.6)
cluster14 <- FindClusters(cluster14, resolution = 0.8)
cluster14 <- RunUMAP(cluster14, reduction = "harmony", dims = 1:10)
cluster14.genes <- rownames(cluster14) 
      cluster14 <- ScaleData(cluster14, features = cluster14.genes)
DimPlot(cluster14, reduction = "umap", label = TRUE, group.by = "seurat_clusters", label.size = 5)
cluster14.markers <- FindAllMarkers(cluster14, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
write.table(cluster14.markers,"cluster14_allmarkers.txt")
saveRDS(cluster14, "filename.RDS")
top5 <- cluster14.markers %>%
    group_by(cluster) %>%
    top_n(n = 20, wt = avg_log2FC)
pdf("DEGs_heatmap_cluster4.pdf")
DoHeatmap(cluster14, features = top5$gene, angle = 45)
dev.off()

##proprtion
prop.table(table(Idents(cluster14)))
prop.table(table(Idents(cluster14), cluster14$condition), margin = 2)
cluster14 <-AddModuleScore(object = cluster14, features =list(MGnD_sig, Homeostasis_MG_sig), name = c("MGnD signature", "Homestasis signature"))

VlnPlot(object = cluster14, features =  c("MGnD.signature1", "Homestasis.signature2"), ncol=2)
VlnPlot(object = cluster14, features = c("MGnD.signature1", "Homestasis.signature2"), split.by = 'condition', combine = FALSE, stack = TRUE, flip = TRUE, split.plot = TRUE) 

FeaturePlot(cluster14, reduction = "umap", features = c("C1qa", "C1qb", "C1qc", "Cd14", "Siglech",  "Cd86",
"Apoc1", "Apoe", "Dab2", "Lgmn", "Ctsd", "Trem2"), order = TRUE, label = TRUE, label.size=5)
FeaturePlot(cluster14, reduction = "umap", features = c("Cd9", "Fcgr3", "Ly6c2", "Ccr2", "Pglyrp1", "Lyz2", "Chil3", "Hp", "Ifitm6", "Msrb1", "Ccl12", "Fn1", "Cd14", "S100a6", "S100a4", "S100a11"), order = TRUE, label = TRUE, label.size=5)

DotPlot(cluster14, features = c("Clec7a", "Lgals3", "Gpnmb", "Itgax", "Spp1", "Ccl2", "Fabp5",
              "Bhlhe40", "Trem2", "Apoe", "Csf1", "Msr1", "Tfec", "Tyrobp",
              "Ctsb", "Ctsd", "Ctsl", "B2m", "Fth1", "Lyz2", "Axl", "Cst7",
              "Lpl", "Cd9",  "Ccl6", "Lilrb4a", "Timp2", "Cd63", "Ly9", "Hif1a"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))
DotPlot(cluster14, features = c("Smad3", "Hexb", "P2ry12", "Mertk", "Entpd1", "Tmem119", "Tgfbr1",
                        "Spi1", "Mafb", "Mef2a", "Sall1", "Egr1", "Jun", "Siglech"), dot.scale = 8, split.by = "condition", cols=c("gray", "red")) +theme(axis.text.x = element_text(angle=90))
```

## Heatmap for microglia sign
```{r}
MGnD_sig <- c("Clec7a", "Lgals3", "Gpnmb", "Itgax", "Spp1", "Ccl2", "Fabp5",
              "Bhlhe40", "Trem2", "Apoe", "Csf1", "Msr1", "Tfec", "Tyrobp",
              "Ctsb", "Ctsd", "Ctsl", "B2m", "Fth1", "Lyz2", "Axl", "Cst7",
              "Lpl", "Cd9", "Csf1", "Ccl6", "Lilrb4a", "Timp2", "Cd63", "Ly9", "Hif1a")

Homeostasis_MG_sig <- c("Smad3", "Hexb", "P2ry12", "Mertk", "Entpd1", "Tmem119", "Tgfbr1",
                        "Spi1", "Mafb", "Mef2a", "Sall1", "Egr1", "Jun", "Siglech")

DoHeatmap(cluster14, features = MGnD_sig, angle = 45)
DoHeatmap(cluster14, features = Homeostasis_MG_sig, angle = 45)
```

## Tim3 expression
```{r}
DotPlot(cluster14, features = c( "Havcr1", "Sema4a", "Havcr2", "Timd4"), cols = c("gray", "red"), dot.scale = 8, split.by = "condition") + RotatedAxis()
VlnPlot(object = cluster14, features = c( "Havcr1", "Sema4a", "Havcr2", "Timd4"), split.by = 'condition', combine = FALSE, stack = TRUE, flip = TRUE, split.plot = TRUE) 


VlnPlot(object = cluster14, features = c("MGnD.signature1", "Homestasis.signature2"), split.by = 'condition', combine = FALSE, stack = TRUE, flip = TRUE, split.plot = TRUE) 
VlnPlot(object = cluster14, features = c("Havcr1", "Sema4a", "Havcr2", "Timd4"), split.by = 'condition', combine = FALSE,group.by = "seurat_clusters",  stack = TRUE, flip = TRUE, split.plot = TRUE)
```

##sanity check genes plots
```{r}
FeaturePlot(cluster14, reduction = "umap", features = c("Cst7", "Clec7a", "Apoe", "Axl", "Itgax", "Lilrb4", "Lpl", "Ly9", "Trem2", "P2ry12", "Tmem119", "Mertk", "Cd80", "Cd86", "C1qc", "Il1a", "Cx3cr1"), order = TRUE, label = TRUE, label.size=5)
FeaturePlot(cluster14, reduction = "umap", features = c("Il1b", "Il6", "Tnf", "Cd68", "Lag3", "Vsir", "Pdcd1", "Pdl1", "Cd200r1", "Mertk", "Cd169", "Ccr2",  "Cd64", "Clec12a", "Cd206", "Cd36", "Cd39"), order = TRUE, label = TRUE, label.size=5)

```


